# Generated by Django 2.2.1 on 2019-05-30 16:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TodoList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todo_content', models.CharField(max_length=200)),
                ('is_completed', models.BooleanField()),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('last_mod', models.DateTimeField(verbose_name='lastest modified date time')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
